# Generated by Django 5.0.1 on 2026-05-03 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('INSTAGRAM', 'Instagram'), ('FACEBOOK', 'Facebook'), ('TWITTER', 'Twitter'), ('LINKEDIN', 'LinkedIn'), ('YOUTUBE', 'YouTube'), ('PINTEREST', 'Pinterest')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to='client.client')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.platform')),
            ],
            options={
                'unique_together': {('client', 'platform')},
            },
        ),
    ]
