# Generated by Codex on 2026-05-11

import django.db.models.deletion
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0002_platform_clientplatform"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="contact_number",
            field=models.CharField(default="", blank=True, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="client",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="client_logos/"),
        ),
        migrations.AddField(
            model_name="client",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now, auto_now=True),
            preserve_default=False,
        ),
        migrations.RenameField(
            model_name="smh",
            old_name="created_at",
            new_name="joined_at",
        ),
        migrations.AddField(
            model_name="smh",
            name="experience_years",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="smh",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="platform",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now, auto_now_add=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Package",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("duration", models.CharField(choices=[("MONTHLY", "Monthly"), ("QUARTERLY", "Quarterly"), ("YEARLY", "Yearly")], max_length=20)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("post_limit", models.PositiveIntegerField(default=0)),
                ("platform_limit", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("notification_type", models.CharField(choices=[("POST_APPROVAL", "Post Approval"), ("POST_APPROVED", "Post Approved"), ("POST_REJECTED", "Post Rejected"), ("POST_FAILED", "Post Failed"), ("PACKAGE_EXPIRY", "Package Expiry"), ("REPORT_READY", "Report Ready")], max_length=30)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("client", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="client.client")),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(blank=True, max_length=255)),
                ("caption", models.TextField()),
                ("hashtags", models.TextField(blank=True)),
                ("media", models.FileField(blank=True, null=True, upload_to="post_media/")),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("PENDING_APPROVAL", "Pending Approval"), ("APPROVED", "Approved"), ("REJECTED", "Rejected"), ("SCHEDULED", "Scheduled"), ("POSTED", "Posted"), ("FAILED", "Failed")], default="DRAFT", max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("client", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="client.client")),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="client.smh")),
            ],
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("month", models.CharField(max_length=20)),
                ("total_posts", models.PositiveIntegerField(default=0)),
                ("total_reach", models.PositiveIntegerField(default=0)),
                ("total_engagement", models.PositiveIntegerField(default=0)),
                ("followers_gained", models.PositiveIntegerField(default=0)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("client", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="client.client")),
            ],
        ),
        migrations.CreateModel(
            name="SocialMediaAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("account_username", models.CharField(max_length=255)),
                ("account_id", models.CharField(blank=True, max_length=255)),
                ("access_token", models.TextField(blank=True)),
                ("refresh_token", models.TextField(blank=True)),
                ("token_expiry", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
                ("client", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="client.client")),
                ("platform", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="client.platform")),
            ],
            options={
                "unique_together": {("client", "platform")},
            },
        ),
        migrations.CreateModel(
            name="ClientSubscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("status", models.CharField(choices=[("ACTIVE", "Active"), ("EXPIRED", "Expired"), ("CANCELLED", "Cancelled")], default="ACTIVE", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("client", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="client.client")),
                ("package", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="client.package")),
            ],
        ),
        migrations.CreateModel(
            name="PostApproval",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("PENDING", "Pending"), ("APPROVED", "Approved"), ("REJECTED", "Rejected")], default="PENDING", max_length=20)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("post", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="client.post")),
            ],
        ),
        migrations.CreateModel(
            name="PostPlatform",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("platform", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="client.platform")),
                ("post", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="client.post")),
            ],
            options={
                "unique_together": {("post", "platform")},
            },
        ),
        migrations.CreateModel(
            name="PostSchedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("scheduled_time", models.DateTimeField()),
                ("posted_time", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(choices=[("PENDING", "Pending"), ("COMPLETED", "Completed"), ("FAILED", "Failed")], default="PENDING", max_length=20)),
                ("failure_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("post", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="client.post")),
            ],
        ),
    ]
