# Generated by Django 4.2.7 on 2026-05-18 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_add_instagram_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='organization_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='clientplatform',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
    ]
