# Generated by Django 5.0.1 on 2026-05-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_remove_post_client_post_clients_post_created_by_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postplatform',
            name='platform_caption',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='postplatform',
            name='platform_media',
            field=models.FileField(blank=True, null=True, upload_to='post_media/platforms/'),
        ),
        migrations.AddField(
            model_name='postplatform',
            name='platform_metadata',
            field=models.JSONField(default=dict),
        ),
    ]
