# Generated by Django 5.0.1 on 2026-06-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_postplatform_platform_caption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediaaccount',
            name='instagram_business_account_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='page_access_token',
            field=models.TextField(blank=True),
        ),
    ]
