# Generated by Django 5.0.1 on 2026-06-03 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_client_bio_client_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace_name', models.CharField(default='SocialManager Pro', max_length=255)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=100)),
                ('theme_color', models.CharField(default='#031B4E', max_length=20)),
                ('default_posting_time', models.TimeField(default='18:00')),
                ('ai_caption_style', models.CharField(default='Professional', max_length=50)),
                ('default_platform', models.CharField(default='Instagram', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('smh', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='client.smh')),
            ],
        ),
    ]
