# Generated by Django 6.0.7 on 2026-08-03 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_expand_client_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='organization_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='clientplatform',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
        migrations.CreateModel(
            name='ClientPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_post_approval', models.BooleanField(default=True)),
                ('notify_post_approved', models.BooleanField(default=True)),
                ('notify_post_rejected', models.BooleanField(default=True)),
                ('notify_post_failed', models.BooleanField(default=True)),
                ('notify_report_ready', models.BooleanField(default=True)),
                ('notify_package_expiry', models.BooleanField(default=True)),
                ('email_digest', models.BooleanField(default=False)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='client.client')),
            ],
        ),
    ]
