# Generated by Django 5.0.1 on 2026-05-19 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_client_organization_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='client',
        ),
        migrations.AddField(
            model_name='post',
            name='clients',
            field=models.ManyToManyField(related_name='posts', to='client.client'),
        ),
        migrations.AddField(
            model_name='post',
            name='created_by_role',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('SMH', 'SMH')], default='SMH', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('NOW', 'Post Now'), ('SCHEDULED', 'Scheduled')], default='NOW', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.smh'),
        ),
    ]
