# Generated by Django 6.0.7 on 2026-08-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_client_organization_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smh',
            name='agency_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='smh',
            name='notify_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='smh',
            name='notify_push',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='smh',
            name='notify_weekly',
            field=models.BooleanField(default=True),
        ),
    ]
