# Generated by Django 5.0.1 on 2026-06-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_socialmediaaccount_instagram_business_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
