export default function ContentQueue() {
  return (
    <div className="p-xl max-w-6xl mx-auto">
      <h1 className="font-headline-xl text-headline-xl text-on-surface mb-xs">Content Queue</h1>
      <p className="text-body-md text-outline mb-xl">Review and approve content before it goes live.</p>
      
      <div className="bg-surface-container-lowest p-xl rounded-xl border border-surface-variant flex flex-col items-center justify-center text-center gap-md min-h-[400px]">
        <span className="material-symbols-outlined text-[64px] text-outline/30">auto_stories</span>
        <h2 className="font-headline-md text-on-surface">No content in queue</h2>
        <p className="text-body-md text-outline max-w-sm">
          Everything is processed! New content generated by AI or uploaded by your team will appear here for review.
        </p>
        <button className="bg-primary text-on-primary px-lg py-md rounded-lg font-bold shadow-md">
          Create New Post
        </button>
      </div>
    </div>
  );
}
